style: github
template: CHANGELOG.tpl.md
info:
  title: Changelog
  repository_url: https://github.com/Cephy314/UsbVendorsLibrary
options:
  tag_filter_pattern: '^v\d+\.\d+\.\d+$'
  commits:
    sort_by: Scope
  commit_groups:
    group_by: Type
    sort_by: Title
    title_order:
      - What's New
      - Fixed
      - Performance
      - Other Updates
    title_maps:
      feat: What's New
      fix: Fixed
      perf: Performance
      chore: Other Updates
      docs: Other Updates
      refactor: Other Updates
      test: Other Updates
      build: Other Updates
      ci: Other Updates
  header:
    pattern: "^(?P<Type>[a-zA-Z]+)(?:\\((?P<Scope>[^)]+)\\))?: (?P<Subject>.+)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
